package bycompany;

public class Ids {
	public static String golSubmitLoopSearch = "id('search')/div[3]/a";
	public static String FlyingTime_CSS = ".duracao-voo";
	public static String Flight_Code_CSS = ".voo-titulo";
	public static String Fligh_Inbound_CSS = ".chegada-voo";
	public static String Flight_Outbound_CSS = ".saida-voo";
	public static String CONTENT_TARIFAS_CSS = ".contentTarifas";
	public static String CONTENT_FLIGHT_CSS = ".contentFlight";
	public static String golDropDownListDestination = "id('fs_popUp_destinations[0]')/ul/li";
	public static String golDropDownListOrigin = "id('fs_popUp_origins[0]')/ul/li";
	public static String golResultsDeparture = "id('site')/div[6]/div[3]/div";
	public static String golResultsReturn = "id('site')/div[7]/div[3]/div";
	public static String golSubmitFirstSearch = "id('toCategory')/a";
	public static String golInputReturnDay = "id('datepickerInputVolta')";
	public static String golInputTripDay = "id('datepickerInputIda')";
	public static String golInputLoginxPath = "id('s_3_1_8_0')";
	public static String golInputPswdxPath = "id('s_3_1_9_0')";
	public static String golSubmitLoginxPath = "id('s_3_1_11_0')";
	public static String golGoToTicketsId = ".//*[@id='s_4_1_4_0']";
	public static String golOneWayxPath = ".//*[@id='tripRadio']/li[2]/input";
	public static String golFromxPath = "id('fs_container_origins[0]')/a";
	public static String golToxPath = "id('fs_container_destinations[0]')/a";
	public static String golInternalFramexPath = ".//*[@id='symbUrlIFrame2']";
	public static String golClientFrame = "_sweclient";
	public static String golContentFrame = "_swecontent";
	public static String golViewFrame = "_sweview";
	public static String multiPlusMilesxPath = ".//*[@id='passenger_useMyPoints']";
	public static String multiPlusOneWayXpath = ".//*[@id='oneway']";
	public static String multiPlusReturnDatexPath = ".//*[@id='search_inbound_date']";
	public static String multiPlusOriginxPath = ".//*[@id='search_from']";
	public static String multiPlusDestinationxPath = ".//*[@id='search_to']";
	public static String multiPlusFlightDatexPath = ".//*[@id='search_outbound_date']";
	public static String multiPlusSubmitFirstxPath = ".//*[@id='onlineSearchSubmitButton']";
	public static String multiPlusResultTableFlightxPath = ".//*[@id='outbound_list_flight_direct']/tbody";
	public static String multiPlusResultTableReturnsxPath = ".//*[@id='inbound_list_flight_direct']/tbody";
	public static String multiPlusFlight_CSS = ".flight";
	public static String multiPlusTD_CSS = "td";
}
